version: '3.4'

services:

  tododb:
    image: postgres

  projectdb:
    image: postgres


  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: Services/Todo/TodoApi/Dockerfile

volumes:
  postgres_todo:
  postgres_project:

