version: '3.4'

services:

  tododb:
    image: postgres

  projectdb:
    image: postgres

  notificationdb:
    image: postgres

  messagebroker:
    image: rabbitmq:management


  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: Services/Todo/TodoApi/Dockerfile

  projectapi:
    image: ${DOCKER_REGISTRY-}projectapi
    build:
      context: .
      dockerfile: Services/Project/ProjectApi/Dockerfile

  notificationapi:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: Services/Notification/NotificationApi/Dockerfile

volumes:
  postgres_todo:
  postgres_project:
  postgres_notification:



