global using ProjectDomain.Models;
global using ProjectApplication.Dtos;
global using Common.CQRS;
global using ProjectApplication.Repositories;
global using MassTransit;
global using MediatR;
global using Common.MessageEvents;
global using Microsoft.Extensions.Logging;
global using ProjectDomain.Events;