global using Microsoft.EntityFrameworkCore;
global using TodoApi.Models;
global using TodoApi.Repositories;
global using TodoApi.Exceptions;
global using Mapster;
global using System.ComponentModel.DataAnnotations;
global using TodoApi.TodoUseCases.CreateTodo;
global using TodoApi.TodoUseCases.GetTodo;
global using TodoApi.TodoUseCases.GetTodos;
